# Generated by Django 3.0.6 on 2020-06-04 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200604_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybills',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
