# Generated by Django 3.0.6 on 2020-06-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200604_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlybills',
            name='name',
        ),
        migrations.AddField(
            model_name='monthlybills',
            name='description',
            field=models.CharField(max_length=2200, null=True),
        ),
    ]
