# Generated by Django 3.0.6 on 2020-06-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200605_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlybills',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='monthlybills',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
